### ISSUE TITLE
"Iterating over objects and arrays: frequent errors": syntax error in example

### ISSUE THREAD

**Issue by jwilk** [victoriadrake/victoriadrake.github.io#1]
This [example](https://victoria.dev/blog/iterating-over-objects-and-arrays-frequent-errors/#alter-nested-property-values):
```js
var fruits: breakfast['fruit'];
for (f in fruits) {
    fruits[f] += 1;
}
console.log(fruits);
```
is not syntactically correct.
I guess it should be `=`, not `:`, in the first line.

**Comment by victoriadrake** [comment]
Thanks for letting me know Jakub! I’ve updated the article.
