### ISSUE TITLE
Add search to Hugo static sites with Lunr Questions

### ISSUE THREAD

**Issue by hathawayj** [victoriadrake/victoriadrake.github.io#4]
**Is your feature request related to a problem? Please describe.**

I appreciate your post on adding search to my Hugo blog.  I have followed the directions but I can't seem to get the search to render results.  I don't see a space to post questions on your blog so I am posting here.

**Describe the solution you'd like**

Help me with my inability to implement your example.

**Describe alternatives you've considered**
Give up and cry.

**Additional context**

My blog uses blogdown from R that builds using Hugo.  I am using Netlify.  I changed your `search-index.html` to search all pages with `{{ range .Site.Pages }}`.  

I can see the [search page on my blog](https://www.mostmovedmover.com/search/) but it doesn't return any results. I would appreciate any suggestions.

**Comment by victoriadrake** [comment]
Hi! I went to take a look but it seems you've switched things up by now. I haven't used blogdown myself so I bet there are some quirks there. If you have a public repo I can take a peek. I'll open this up for other help in the meantime!

**Comment by hathawayj** [comment]
Yeah.  I went through at least three other guides that were much like yours.  All ended in the same failure.  I think you are on to something with the blogdown comment.  I moved it all back to be based on your guide.

[Search on my blogdown blog](https://www.mostmovedmover.com/search/).  I will look into blogdown issues as well.  I also added you to my repo so that you can see my full directory.

Maybe this will help - https://github.com/yihui/hugo-prose/issues/9.

https://github.com/hathawayj/mostmovedmover.com/invitations
