### ISSUE TITLE
Broken RSS feed

### ISSUE THREAD

**Issue by SISheogorath** [victoriadrake/victoriadrake.github.io#5]
**Describe the bug**
It seems like the RSS feed contains a lot more than expected with titles that are not intended for the human eye.

**To Reproduce**
1. Go to 'https://victoria.dev/index.xml'
2. Check the content of `<title>` tags
3. Realise that `7dfe5d66-2ad6-47de-a7aa-e647afd0d87a` isn't the most interesting title.

**Expected behavior**
I would expect that GUIDs continue to be the same and that title's are intended for the human eye and not just some UUID.

**Screenshots**

![Screenshot of the view in feedreader](https://user-images.githubusercontent.com/8719867/119279239-aeaaa780-bc2a-11eb-8f2e-3a84bae1e08c.png)

**Comment by victoriadrake** [comment]
Thank you very much!
